CREATE TABLE Tokens (
    id INT PRIMARY KEY AUTO_INCREMENT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT(CURRENT_TIMESTAMP),
    expires_at TIMESTAMP NOT NULL,
    user_id INT NOT NULL,
    random VARCHAR(255) NOT NULL

); 
